"""Provider-neutral market and macro data contracts for PineForge."""

from .backtest import (
    BacktestOptions,
    BacktestReport,
    EngineBacktestError,
    MagnifierDistribution,
    PineForgeBacktestRunner,
)
from .docker_runtime import (
    DockerBacktestRuntime,
    DockerExecutionError,
    DockerPrerequisiteError,
    discover_repository_root,
)
from .engine import EngineStreamSink, PfBar, PfTradeTick, pack_bars, pack_trade_ticks
from .errors import EngineStreamError
from .models import (
    AssetClass,
    Bar,
    ContractSpec,
    Instrument,
    MacroObservation,
    MarketListing,
    MarketType,
    OptionType,
    TradeTick,
)
from .providers import (
    CcxtCapabilityError,
    CcxtDataError,
    CcxtDependencyError,
    CcxtError,
    CcxtProvider,
    HistoricalBarProvider,
    LiveTradeProvider,
    MacroDataProvider,
    MarketCatalogProvider,
    MarketDataProvider,
    MarketNotFoundError,
    ProviderFactory,
    ProviderNotFoundError,
    ProviderRegistry,
    ProviderRegistryError,
    create_provider,
    default_registry,
)
from .requests import BarRequest, MacroRequest, MarketQuery, TradeSubscription

__all__ = [
    "AssetClass",
    "BacktestOptions",
    "BacktestReport",
    "Bar",
    "BarRequest",
    "CcxtCapabilityError",
    "CcxtDataError",
    "CcxtDependencyError",
    "CcxtError",
    "CcxtProvider",
    "ContractSpec",
    "DockerBacktestRuntime",
    "DockerExecutionError",
    "DockerPrerequisiteError",
    "EngineBacktestError",
    "EngineStreamError",
    "EngineStreamSink",
    "HistoricalBarProvider",
    "Instrument",
    "LiveTradeProvider",
    "MacroDataProvider",
    "MacroObservation",
    "MacroRequest",
    "MagnifierDistribution",
    "MarketCatalogProvider",
    "MarketDataProvider",
    "MarketListing",
    "MarketNotFoundError",
    "MarketQuery",
    "MarketType",
    "OptionType",
    "PfBar",
    "PfTradeTick",
    "PineForgeBacktestRunner",
    "ProviderFactory",
    "ProviderNotFoundError",
    "ProviderRegistry",
    "ProviderRegistryError",
    "TradeSubscription",
    "TradeTick",
    "create_provider",
    "default_registry",
    "discover_repository_root",
    "pack_bars",
    "pack_trade_ticks",
]
